name: librahub-content

services:
  content-api:
    build:
      context: ../..
      dockerfile: services/Content/Dockerfile
    container_name: librahub-content-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__ContentDb=Host=librahub-postgres;Port=5432;Database=librahub_content;Username=librahub_admin;Password=L1br@Hub_DB_2026!S3cur3_P@ss
      - ConnectionStrings__RabbitMQ=amqp://librahub_mq:R%40bb1tMQ_L1br%40Hub_2026%21S3cur3_P%40ss@librahub-rabbitmq:5672/
      - Storage__Endpoint=librahub-minio:9000
      - ReadAccess__CatalogApiUrl=http://librahub-catalog-api:8080
      - ReadAccess__LibraryApiUrl=http://librahub-library-api:8080
      - EmailConfig__Host=papercut-smtp
      - InternalAccess__ApiKey=librahub_internal_dev_2026
    ports:
      - "60970:8080"
      - "60971:8081"
    networks:
      - librahub-network
    restart: unless-stopped

networks:
  librahub-network:
    external: true
    name: librahub-network

